server:
  port: 9000
spring:
  application:
    name: RibbonEurekaInvoker
RibbonEurekaProvider:
  ribbon:
    NFLoadBalancerRuleClassName:  com.zw.eureka.MyRule
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/