spring:
  application:
    name: HealthEurekaProvider
endpoints:
  sensitive: false
eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/