server:
  port: 8081
spring:
  application:
    name: HealthEurekaInvoker
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/